### ISSUE TITLE
Design Questions

### ISSUE THREAD

**Issue by wolberd** [People-Museum-Project/people-museum-backend#1]
class Handler:
   generic name, should this be called PeopleMuseumData or something?

   should addPerson return a person (same for other add/update)
  
   need pagination
       for instance, when i call getPersonListByUserId, how many items do I get returned, how 
       do I get the next batch
       
   naming: getPersonLlistByUserId might be just  getPersonList 
      same for all get/update/remove?
      (assume the  method is by Id unless other info added in name)
      e.g., getCollectionList for when you give a collectionId
      then getCollectionListByUserId could be getColectionListForUser

**Comment by DizzyDoze** [comment]
I'm start working on this issue, please hold it, I will update soon.

**Comment by DizzyDoze** [comment]
1. Pagination and Sorting have been updated for both Person and Collection.
2. Alusi has updated the names of function which is more brief.
3. Class Handler name to be confirmed.
