### ISSUE TITLE
Get the person list and collection list according to the timestamp

### ISSUE THREAD

**Issue by BianYi10** [People-Museum-Project/people-museum-backend#11]
we need another 2 functions to get person  and get collection based on timestamp

**Comment by wolberd** [comment]
Should be a parameter to various methods, client can specify orderbyname or
orderbycreatedby etc

David Wolber
Professor, University of San Francisco
DragAndDropCode.com, AppInventor.org

**Comment by DizzyDoze** [comment]
I'm working on this one.

**Comment by DizzyDoze** [comment]
1. Timestamp for both Person and Collection table has been created.
2. We can now sort by "date" in both tables.
3. Related API doc has also been updated, please check before testing.
