### ISSUE TITLE
Get Functions 

### ISSUE THREAD

**Issue by Kayvan-Zahiri** [People-Museum-Project/people-museum-backend#2]
Which functions can we call to get all the people in the museum for a specific user and all the collections in the museum for a specific user? I've tried a couple, but haven't had any success in doing so. I have attached some screenshots of the terminal below. Thanks.
<img width="1250" alt="Screenshot 2024-07-03 124516" src="https://github.com/People-Museum-Project/people-museum-backend/assets/123409429/cddccb96-8bfc-4219-aefc-633ef85fe5a3">
<img width="1250" alt="Screenshot 2024-07-03 124441" src="https://github.com/People-Museum-Project/people-museum-backend/assets/123409429/f42de678-1e3c-49b1-b661-060a6498b81d">
<img width="1250" alt="Screenshot 2024-07-03 124255" src="https://github.com/People-Museum-Project/people-museum-backend/assets/123409429/eb17552c-bac4-4f40-adba-f38d5c18da5a">
<img width="1250" alt="Screenshot 2024-07-03 124223" src="https://github.com/People-Museum-Project/people-museum-backend/assets/123409429/d2402ea4-67bb-4c97-8f6b-f093fc83614a">

**Comment by DizzyDoze** [comment]
Bugs has been fixed.
Please ensure the type of **userId** is always `STRING` instead of `INTEGER`. 

* set environment variable
`export BASE_URL = http://localhost:8080/db`

1. getPersonList for specific `userId`, example:
```
curl -X POST "$BASE_URL/getPersonList" -H "Content-Type: application/json" -d '{
  "userId": 1
}'
```

2. getCollectionList for specific `userId`, example:
```
curl -X POST "$BASE_URL/getCollectionList" -H "Content-Type: application/json" -d '{
  "userId": 1,
  "page": 1,
  "limit": 10,
  "sortBy": "name",
  "order": "asc"
}' 
```
