### ISSUE TITLE
person maps collections and collection maps people

### ISSUE THREAD

**Issue by BianYi10** [People-Museum-Project/people-museum-backend#5]
A person needs to be able to map multiple collections.(add a list of collectionId in person table or create a new table)
A colletion needs to contain multiple people.(if we use a list of collectionId it will be a little bit troublesome to get all people in one colletion. if we use a new table we need to consider the transaction part, i mean the data safety )

**Comment by DizzyDoze** [comment]
new table PersonCollection has been created. Routers for mapping person to collection added. problem fixed.
