### ISSUE TITLE
Get IDs

### ISSUE THREAD

**Issue by Kayvan-Zahiri** [People-Museum-Project/people-museum-backend#7]
Could you add functions to get a persons name/id and a collections name/id? This would help with handling individuals better and calling the other existing functions. Thanks.

**Comment by wolberd** [comment]
id should come with any person previously obtained, e.g., when you getUsersPersons each person has id and other properties. So I don't think you need a method to get an id

In your Javascript client, you want to create methods that create a Person (or PersonList) object as a result of such calls, andd that object should include the id

**Comment by Kayvan-Zahiri** [comment]
I tried and think that the id number from the Name/ID column in the table isn't accessible from people in getPersonList. Objects are not valid as a React child (found: object with keys {collectionId, context, description, imageLink, name, public, userId}).

**Comment by Alas129** [comment]
This issue is fixed. Currently we could git pull and test it locally, I'll deploy the the server later.
