### ISSUE TITLE
getcollectionbyperson

### ISSUE THREAD

**Issue by BianYi10** [People-Museum-Project/people-museum-backend#8]
A person needs to be able to map multiple collections.(add a list of collectionId in person table or create a new table)
now we need a fucntion that we can use one personid to get multiple collectionid.

**Comment by DizzyDoze** [comment]
working on this one.

**Comment by DizzyDoze** [comment]
1. get collection list by personId endpoint added. 
2. unique compose key for PersonCollection table added.
3. all data in PersonCollection table has been cleaned, please feel free to add new ones for testing.
