### ISSUE TITLE
get a person list in a certain user but not belong to a colletion 

### ISSUE THREAD

**Issue by BianYi10** [People-Museum-Project/people-museum-backend#9]
I want get a personlist  who belong to a user but are not part of a certain collection.
input parameter should be userid and colletionid
output should be a person list

**Comment by wolberd** [comment]
Taking in Yi's two togehter, we need "getColllectionsByPerson"...
we also need "complement" methods, "getCollectionsPersonNotIn" and "getPersonsNotInCollection". These two
are needed when user is adding/removing people to/from collections or

**Comment by Alas129** [comment]
I'm working on this issue

**Comment by Alas129** [comment]
Done
